
== Best practices for using {partner-product-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

* By default, only one application node is created per cluster. Run *zebclient-interactive* from the command line and select Update to add application nodes for extra performance when needed. To save cost, remove the additional application nodes as soon as they no longer needed. +

* To change the performance and redundancy level, a new ZebClient cluster needs to be deployed. Data must be moved from the old to new cluster using either an S3 or a file system interface.

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

ZebClient eliminates the need for separate backup data storage. +

ZebClient writes data to hot and warm disks as well as to cold and durable cloud storage, thereby securing data protection and data availability.

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

For additional information about ZebClient and ZebClient use cases, please visit https://www.zebware.com/products/zebclient/[zebware.com,window=read-later] or https://zebware.gitlab.io/devops/zebclient-docs/[ZebClient Docs,window=read-later]