=== Install ZebClient CLI

The ZebClient CLI (Command Line Interface) is required to deploy ZebClient in the AWS Cloud.

=== Prerequisites

* Programming language https://www.python.org/downloads/[Python 3,window=read-later] and package manager https://pip.pypa.io/en/stable/[pip,window=read-later] must be installed.
* A ZebClient license key must be available.
* Credentials to a cloud service provider.

Note that trial and production licenses are ordered in the https://www.zebware.com/store[/Zebware store,window=read-later]. Based on what ZebClient package is selected in the Zebware store, the ZebClient CLI is tailored to deploy the contents of that package. When selecting to try or buy a new package, a new license and a new account must be created . When registering an account, it is recommended to use a generic email address like engineering@domain.com

=== Installation

Zebware store provides a ZebClient CLI download link formatted as a ZIP-file . The CLI supports installation on:

* Linux
* MacOS
* Windows
* arm64 and x86_64 +

Use pip to install ZebClient CLI. Root access is required in Linux. Please add sudo before the installation command.

[source,ruby]
----
pip install <file name>
----

=== Use ZebClient CLI
[,ruby]
----
zebclient-interactive
----

Select “Install” and answer a few configuration questions to deploy ZebClient. +

One of the questions is ZEBCLIENT_ENDPOINT_URL [https://api.zebware.com/api/v1]: +

Press enter to use the default value. +

An email will be sent when ZebClient is ready to be used. This takes about 15-30 minutes depending on the cluster size/ZebClient package selected.

=== Get access to ZebClient

Wait until the confirmation email states that ZebClient is ready. +

Start ZebClient CLI. +

[source,ruby]
----
zebclient-interactive
----

Download SSH Keys named id_rsa. +

For Linux: Run this command to change access rights for the id_rsa file: +

[source,ruby]
----
chmod 0600 id_rsa
----

For Windows:

* Use Explorer and navigate to the folder with id_rsa and the type powershell in the field for file path.
* Powershell will now open in the folder with the id_rsa file.
* Run the following commands to change the access rights for the id_rsa file:

[source,ruby]
----
icacls.exe id_rsa /reset
----

[source,ruby]
----
icacls.exe id_rsa /grant:r "$($env:username):(r)"
----

[source,ruby]
----
icacls.exe id_rsa /inheritance:r
----

Start ZebClient CLI again and download the Inventory. +

Open the inventory with a text editor and locate headline Agents. The IP-address(es) is the Agent(s) to connect to the ZebClient. Use the Agent(s) IP-address to connect:

[source,ruby]
----
ssh -i ida_rsa ubuntu@<ip-address>
----

Change to file system directory:

[source,ruby]
----
cd /fs
----

Create your own folder:

[source,ruby]
----
mkdir <folder name>
----

Open the folder:

[source,ruby]
----
mkdir <folder name>
----

Open the folder:

[source,ruby]
----
cd <folder name>
----

*ZebClient is now ready to be used to improve data performance & redundancy.* +

NOTE: The ZebClient supports scale-out/scale-in of application nodes once the cluster has been created.

